/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tianxiabuyi_txutils_util_KeyUtils */

#ifndef _Included_com_tianxiabuyi_txutils_util_KeyUtils
#define _Included_com_tianxiabuyi_txutils_util_KeyUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tianxiabuyi_txutils_util_KeyUtils
 * Method:    something
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tianxiabuyi_txutils_util_KeyUtils_something
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
